import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Special_Elite } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
const specialElite = Special_Elite({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={specialElite.className}>{children}</body>
      </html>
    </ClerkProvider>
  )
}
